### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by tylerb** [jackspirou/grind#1]
```
go get github.com/jackspirou/grind
# github.com/jackspirou/grind/vardecl
../../jackspirou/grind/vardecl/vardecl.go:89: xScope.Pos undefined (type *types.Scope has no field or method Pos)
../../jackspirou/grind/vardecl/vardecl.go:89: too many arguments in call to types.Eval
```

```
go version
go version go1.5.2 darwin/amd64
```

**Comment by jackspirou** [comment]
Im guessing its an issue with `go1.5.2` since I am still on `go1.5.1`.  Upgrading now :)

**Comment by tylerb** [comment]
Cool! Thanks for looking in to it.

**Comment by jackspirou** [comment]
@tylerb I am unable to reproduce the errors you are getting even when when I run `go get github.com/jackspirou/grind` with `go version go1.5.2 darwin/amd64`.

I did take a look at the errors reported above and they don't seem to make sense with `go version go1.5.2`.

> first error: vardecl.go:89: xScope.Pos undefined (type *types.Scope has no field or method Pos)

The method `Pos()` that is attached to `*types.Scope` can be found [here](https://godoc.org/golang.org/x/tools/go/types#Scope.Pos).

> second error: vardecl.go:89: too many arguments in call to types.Eval

Here is the line: `xt, err := types.Eval(pkg.FileSet, pkg.Types, xScope.Pos(), xs)` and it has 4 parameters. The current method `Eval` in the docs can be found [here](https://godoc.org/golang.org/x/tools/go/types#Eval) and it also has 4 arguments of the correct types.

**This leads me to think that *maybe* the `golang.org/x/tools/go/types` package you have installed on your local machine is potentially old or out of date?**

Just for the sake of being transparent, here is the verbose output I get after removing the `grind` binary, removing the repo from my `GOPATH` and then running `go get github.com/jackspirou/grind`.  

```bash
$ go get -u -v github.com/jackspirou/grind
github.com/jackspirou/grind (download)
Fetching https://golang.org/x/tools/go/gcimporter?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/gcimporter?go-get=1 (status code 200)
get "golang.org/x/tools/go/gcimporter": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/gcimporter?go-get=1
get "golang.org/x/tools/go/gcimporter": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
Fetching https://golang.org/x/tools/go/exact?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/exact?go-get=1 (status code 200)
get "golang.org/x/tools/go/exact": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/exact?go-get=1
get "golang.org/x/tools/go/exact": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/types?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/types?go-get=1 (status code 200)
get "golang.org/x/tools/go/types": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/types?go-get=1
get "golang.org/x/tools/go/types": verifying non-authoritative meta tag
github.com/jackspirou/grind/block
github.com/jackspirou/grind/flow
github.com/jackspirou/grind/grinder
github.com/jackspirou/grind/deadcode
github.com/jackspirou/grind/gotoinline
github.com/jackspirou/grind/vardecl
github.com/jackspirou/grind
```

Let me know what you think of the above and if you can confirm your `golang.org/x/tools/go/types` package is current.   Thanks!

**Comment by tylerb** [comment]
Well that's bizarre. I must have something messed up on my end. I'll take a look. Thanks!

**Comment by tylerb** [comment]
Looks like I had edited the golang.org/x/tools directory at some point in the past, causing it to fail to pull it via `go get`. Thanks!

**Comment by shurcooL** [comment]
@tylerb, FWIW (and excuse my shameless plug), you could use the tool [`gostatus`](https://github.com/shurcooL/gostatus#readme) to debug/confirm issues like this. I made it because I had run into problems like this when working on many things at the same time, and wanted something to check the status of my Go repos so I could be more confident about what I was doing.
